const imagePath = (folder, filename) =>
  encodeURI(`/images/${folder}/${filename}`);

export const projects = [
  {
    id: "mrs-shika-thally",
    title: "Mrs. Shika Residence",
    category: "Farmhouse",
    location: "Thally",
    year: "2026",
    description: "A bespoke farmhouse project designed and built for Mrs. Shika in Thally.",
    features: ["Custom farmhouse design", "Quality construction", "Site-specific planning"],
    images: [
      imagePath("Mrs. Shika - Thally", "IMG-20260722-WA0008.jpg"),
      imagePath("Mrs. Shika - Thally", "IMG-20260722-WA0007.jpg"),
      imagePath("Mrs. Shika - Thally", "IMG-20260722-WA0006.jpg"),
    ],
  },
  {
    id: "mr-rajesh-thally",
    title: "Mr. Rajesh Residence",
    category: "Farmhouse",
    location: "Thally",
    year: "2026",
    description: "A farmhouse project completed for Mr. Rajesh in Thally.",
    features: ["Custom farmhouse design", "Quality construction", "Site-specific planning"],
    images: [
      imagePath("Mr. Rajesh - Thally", "IMG-20260723-WA0015.jpg"),
      imagePath("Mr. Rajesh - Thally", "IMG-20260723-WA0014.jpg"),
      imagePath("Mr. Rajesh - Thally", "IMG-20260723-WA0013.jpg"),
    ],
  },
  {
    id: "mrs-lakshmi-thally",
    title: "Mrs. Lakshmi Residence",
    category: "Farmhouse",
    location: "Thally",
    year: "2026",
    description: "A detailed farmhouse project completed for Mrs. Lakshmi in Thally.",
    features: ["Custom farmhouse design", "Quality construction", "Site-specific planning"],
    images: [
      imagePath("Mrs. Lakshmi - Thally", "IMG-20260722-WA0005.jpg"),
      imagePath("Mrs. Lakshmi - Thally", "IMG-20260722-WA0004.jpg"),
      imagePath("Mrs. Lakshmi - Thally", "IMG-20260722-WA0003.jpg"),
      imagePath("Mrs. Lakshmi - Thally", "IMG-20260722-WA0002.jpg"),
      imagePath("Mrs. Lakshmi - Thally", "IMG-20260722-WA0001.jpg"),
      imagePath("Mrs. Lakshmi - Thally", "IMG-20260722-WA0000.jpg"),
    ],
  },
  {
    id: "mr-vishranth-thally",
    title: "Mr. Vishranth Residence",
    category: "Farmhouse",
    location: "Thally",
    year: "2026",
    description: "A farmhouse project completed for Mr. Vishranth in Thally.",
    features: ["Custom farmhouse design", "Quality construction", "Site-specific planning"],
    images: [imagePath("Mr. Vishranth - Thally", "IMG-20260722-WA0009.jpg")],
  },
  {
    id: "mr-sagar-shoolagiri",
    title: "Mr. Sagar Residence",
    category: "Farmhouse",
    location: "Shoolagiri",
    year: "2026",
    description: "A farmhouse project completed for Mr. Sagar in Shoolagiri.",
    features: ["Custom farmhouse design", "Quality construction", "Site-specific planning"],
    images: [imagePath("Mr. sagar - Shoolagiri", "IMG-20260722-WA0014.jpg")],
  },
  {
    id: "mr-sundar-krishnan-shoolagiri",
    title: "Mr. Sundar Krishnan Residence",
    category: "Farmhouse",
    location: "Shoolagiri",
    year: "2026",
    description: "A farmhouse project completed for Mr. Sundar Krishnan in Shoolagiri.",
    features: ["Custom farmhouse design", "Quality construction", "Site-specific planning"],
    images: [
      imagePath("Mr. Sundar krishnan - Shoolagiri", "IMG-20260722-WA0019.jpg"),
      imagePath("Mr. Sundar krishnan - Shoolagiri", "IMG-20260729-WA0017.jpg"),
      imagePath("Mr. Sundar krishnan - Shoolagiri", "IMG-20260731-WA0085.jpg"),
      imagePath("Mr. Sundar krishnan - Shoolagiri", "IMG-20260729-WA0020(1).jpg"),
      imagePath("Mr. Sundar krishnan - Shoolagiri", "IMG-20260729-WA0019.jpg"),
      imagePath("Mr. Sundar krishnan - Shoolagiri", "IMG-20260729-WA0018.jpg"),
    ],
  },
  {
    id: "mr-om-band-denkanikottai",
    title: "Mr. Om Band Residence",
    category: "Farmhouse",
    location: "Denkanikottai",
    year: "2026",
    description: "A farmhouse project completed for Mr. Om Band in Denkanikottai.",
    features: ["Custom farmhouse design", "Quality construction", "Site-specific planning"],
    images: [
      imagePath("Mr. Om band - Denkanikottai", "IMG-20260722-WA0017(1).jpg"),
      imagePath("Mr. Om band - Denkanikottai", "IMG-20260722-WA0016.jpg"),
      imagePath("Mr. Om band - Denkanikottai", "IMG-20260722-WA0015.jpg"),
    ],
  },
  {
    id: "mr-john-hosur",
    title: "Mr. John Residence",
    category: "Farmhouse",
    location: "Hosur",
    year: "2026",
    description: "A farmhouse project completed for Mr. John in Hosur.",
    features: ["Custom farmhouse design", "Quality construction", "Site-specific planning"],
    images: [
      imagePath("Mr. john - Hosur", "IMG-20260721-WA0039.jpg"),
      imagePath("Mr. john - Hosur", "IMG-20260721-WA0038.jpg"),
      imagePath("Mr. john - Hosur", "IMG-20260721-WA0037.jpg"),
    ],
  },
  {
    id: "mr-nityanandan-jawalgiri",
    title: "Mr. Nityanandan Residence",
    category: "Farmhouse",
    location: "Jawalgiri",
    year: "2026",
    description: "A farmhouse project completed for Mr. Nityanandan in Jawalgiri.",
    features: ["Custom farmhouse design", "Quality construction", "Site-specific planning"],
    images: [
      imagePath("Mr. Nityanandan - Jawalgiri", "IMG-20260722-WA0013.jpg"),
      imagePath("Mr. Nityanandan - Jawalgiri", "IMG-20260722-WA0012.jpg"),
      imagePath("Mr. Nityanandan - Jawalgiri", "IMG-20260722-WA0011.jpg"),
      imagePath("Mr. Nityanandan - Jawalgiri", "IMG-20260722-WA0010.jpg"),
    ],
  },
];

export const projectCategories = ["All", ...new Set(projects.map(({ category }) => category))];
